# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Prod environment
variables:

  # Global
  ap_vm_image: ubuntu-20.04

  namespace: cdtmlopsv2 #Note: A namespace with many characters will cause storage account creation to fail due to storage account names having a limit of 24 characters.
  postfix: 0670
  location: westeurope
  environment: dev
  enable_aml_computecluster: true
  enable_aml_secure_workspace: false
  enable_monitoring: false
  subscription_id: f1dec604-2ef2-4271-af97-21bb6a2eea00


  # Azure DevOps
  ado_service_connection_rg: Azure-ARM-Dev
  ado_service_connection_aml_ws: Azure-ARM-Dev

  

  # DO NOT TOUCH

  # For pipeline reference
  resource_group: rg-$(namespace)-$(postfix)$(environment)
  aml_workspace: mlw-$(namespace)-$(postfix)$(environment)
  application_insights: mlw-$(namespace)-$(postfix)$(environment)
  key_vault: kv-$(namespace)-$(postfix)$(environment)
  container_registry: cr$(namespace)$(postfix)$(environment)
  storage_account: st$(namespace)$(postfix)$(environment)


  # batch-deployment
  endpoint_type: batch
  endpoint_name: PCB-detection